
import { Currency, Language } from '../types';
import { de } from './translations_de';
import { ru } from './translations_ru';
import { sv } from './translations_sv';

export const formatCurrency = (amount: number, currency: Currency, locale: string = 'tr-TR') => {
  return new Intl.NumberFormat(locale, {
    style: 'currency',
    currency: currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

// Notification Helper
export const sendNotification = (title: string, body: string) => {
  if (!('Notification' in window)) return;

  if (Notification.permission === 'granted') {
    new Notification(title, {
      body,
      icon: 'https://cdn-icons-png.flaticon.com/512/201/201623.png',
      silent: false
    });
  } else if (Notification.permission !== 'denied') {
    Notification.requestPermission().then(permission => {
      if (permission === 'granted') {
        new Notification(title, {
          body,
          icon: 'https://cdn-icons-png.flaticon.com/512/201/201623.png'
        });
      }
    });
  }
};

const tr = {
  // Landing Page
  lpHeroTitle: "Butik Otelciliğin",
  lpHeroTitleHighlight: "Yapay Zeka Çağı",
  lpHeroSub: "Aura PMS ile operasyonlarınızı otomatikleştirin, doluluk oranlarını maksimize edin ve misafirlerinize kusursuz bir deneyim sunun.",
  lpCtaStart: "Ücretsiz Başla",
  lpCtaLogin: "Yönetici Girişi",
  lpFeatAI: "Yapay Zeka Asistanı",
  lpFeatAIDesc: "Fiyat stratejileri ve misafir yanıtları için akıllı öneriler.",
  lpFeatSync: "Kanal Senkronizasyonu",
  lpFeatSyncDesc: "Booking, Expedia ve Airbnb ile çift yönlü anlık bağlantı.",
  lpFeatRes: "Akıllı Rezervasyon",
  lpFeatResDesc: "Web sitenizden komisyonsuz, doğrudan rezervasyon alın.",
  lpStat1: "%40 Gelir Artışı",
  lpStat2: "2000+ Mutlu Otel",
  lpStat3: "7/24 Destek",
  lpTestimonial1: "Aura'ya geçtiğimizden beri operasyonel yükümüz yarı yarıya azaldı. Fiyat önerileri inanılmaz!",
  lpTestimonial1Auth: "Zeynep K. - Alaçatı",
  lpTestimonial2: "Arayüz o kadar modern ve hızlı ki, resepsiyon personelimiz eğitim almadan kullanmaya başladı.",
  lpTestimonial2Auth: "Mehmet Y. - Kapadokya",
  lpBenefitTitle: "Neden Aura?",
  lpBenefit1: "Bulut Tabanlı & Güvenli",
  lpBenefit2: "Mobil Uyumlu Yönetim",
  lpBenefit3: "Gelişmiş Raporlama",
  lpFooterText: "Butik oteller için yeni nesil teknoloji.",

  // Sidebar
  dashboard: 'Panel',
  calendar: 'Takvim',
  housekeeping: 'Kat Hizmetleri',
  channels: 'Kanal Yöneticisi',
  reviews: 'Misafir Yorumları',
  bookingEngine: 'Rezervasyon Motoru',
  settings: 'Otel Ayarları',
  guide: 'Kurulum & Kılavuz',
  logout: 'Çıkış Yap',
  role: 'Yönetici',
  websiteBuilder: 'Web Sitesi Yönetimi',
  messages: 'Mesajlar',
  reporting: 'Raporlama',
  invoices: 'Faturalar',
  pricing: 'Fiyat & Müsaitlik',
  theme: 'Tema',
  lightMode: 'Aydınlık Mod',
  darkMode: 'Karanlık Mod',

  // Operations & Maintenance (New)
  operationsCenter: 'Operasyon Merkezi',
  operationsDesc: 'Kat hizmetleri ve teknik bakım yönetimi.',
  maintenance: 'Bakım & Teknik',
  createTicket: 'Arıza Kaydı Oluştur',
  issue: 'Sorun',
  priority: 'Öncelik',
  reported: 'Bildirildi',
  markResolved: 'Çözüldü',
  noTickets: 'Bakım kaydı bulunamadı.',
  reportIssue: 'Sorun Bildir',
  issueDesc: 'Sorun Tanımı',
  submitTicket: 'Kaydı Oluştur',
  selectRoom: 'Oda Seçiniz...',
  priorityLow: 'Düşük',
  priorityMedium: 'Orta',
  priorityHigh: 'Yüksek',
  priorityCritical: 'Kritik',
  statusOpen: 'Açık',
  statusInProgress: 'İşlemde',
  statusResolved: 'Çözüldü',
  reporter: 'Bildiren',

  // Public Website (New)
  navAbout: 'Hakkımızda',
  navRooms: 'Odalar',
  navContact: 'İletişim',
  bookNow: 'Rezervasyon Yap',
  checkAvailability: 'Müsaitlik Kontrolü',
  startFrom: 'Başlangıç Fiyatı',
  viewAll: 'Tümünü Gör',
  ourRooms: 'Odalarımız',
  gallery: 'Galeri',
  welcomePublic: 'Hoşgeldiniz',
  newsletter: 'Bülten',
  join: 'Katıl',
  footerDesc: 'Şehrin kalbinde lüks yaşam.',
  guestExperiences: 'Misafir Deneyimleri',
  contactUs: 'Bize Ulaşın',
  search: 'Ara',
  guests: 'Misafir',
  adults: 'Yetişkin',
  children: 'Çocuk',
  bookYourStay: 'Konaklamanızı Planlayın',

  // Website Builder Defaults
  defaultHeroTitle: 'Cennete Hoşgeldiniz',
  defaultHeroSubtitle: 'Lüks ve konforu keşfedin',
  aboutContent: 'Ege\'nin kalbinde lüksü yaşayın. Dünya standartlarında olanaklarımız ve nefes kesen manzaralarımızın keyfini çıkarmanız için sizi davet ediyoruz.',
  aboutTitle: 'Duyularınız İçin Bir Sığınak',
  mockReview1: 'Harika bir konaklamaydı! Manzara nefes kesici.',
  mockReview2: 'Personel inanılmaz ilgiliydi.',

  // Dashboard Quick Actions
  quickActions: 'Hızlı İşlemler',
  quickNewRes: 'Yeni Rezervasyon',
  quickPricing: 'Fiyatları Güncelle',
  quickHousekeeping: 'Odaları Kontrol Et',
  quickChannel: 'Kanalları Eşitle',

  // Pricing Module & Bulk Update
  pricingTitle: 'Fiyatlandırma & Gelir Yönetimi',
  pricingDesc: 'Yapay zeka destekli içgörülerle fiyatları optimize edin.',
  bulkUpdate: 'Toplu Güncelleme',
  competitors: 'Rakip Analizi',
  smartSuggestions: 'Akıllı Öneriler',
  dateRange: 'Tarih Aralığı',
  applyTo: 'Uygulanacak Oda Tipleri',
  priceUpdate: 'Fiyat Güncelleme',
  inventoryUpdate: 'Müsait Oda',
  stopSale: 'Stop Sale',
  openSale: 'Satışa Aç',
  closeSale: 'Satışa Kapat',
  currentPrice: 'Mevcut Fiyat',
  newPrice: 'Yeni Fiyat',
  applyUpdates: 'Değişiklikleri Uygula',
  competitorName: 'Rakip Otel Adı',
  addCompetitor: 'Rakip Ekle',
  myPrice: 'Sizin Fiyatınız',
  marketAvg: 'Pazar Ortalaması',
  diff: 'Fark',
  suggestionLower: 'Fiyat Düşür',
  suggestionRaise: 'Fiyat Artır',
  suggestionHold: 'Fiyatı Koru',
  suggestionLowerDesc: 'Rakiplerinizden %10 daha pahalısınız. Doluluğu artırmak için indirim önerilir.',
  suggestionRaiseDesc: 'Pazar ortalamasının altındasınız ve talep yüksek. Kârlılığı artırmak için zam yapın.',
  autoAdjust: 'Otomatik Ayarla',
  insightMarket: 'Pazar Konumu',
  insightDemand: 'Talep Uyarısı',
  insightOpportunity: 'Fırsat',
  flashSale: 'Şok Kampanya',
  quickPriceUpdate: 'Hızlı Fiyat Değişimi',
  adjustInventory: 'Stok Düzenle',
  toggleStopSale: 'Stop Sale Aç/Kapa',
  onlinePrice: 'Online Fiyat',
  agencyPrice: 'Acente Fiyatı',
  history: 'Geçmiş',
  changeLog: 'Fiyat Değişim Logları',
  oldVal: 'Eski',
  newVal: 'Yeni',
  user: 'Kullanıcı',
  changeDate: 'İşlem Tarihi',
  targetDate: 'Hedef Tarih',

  // Bulk Update Specific
  applyChangesTo: 'Değişiklikleri Uygula:',
  start: 'Başlangıç',
  end: 'Bitiş',
  applyOnDays: 'Günleri Seç',
  selectAll: 'Tümünü Seç',
  weekdaysOnly: 'Sadece Hafta İçi',
  weekendsOnly: 'Sadece Hafta Sonu',
  bulkNote: 'Not: Değiştirmek istemediğiniz alanları boş bırakın. Sadece doldurulan alanlar seçili tarihlere uygulanacaktır.',
  basePrice: 'Baz Fiyat',
  online: 'Online',
  agency: 'Acente',
  inventory: 'Envanter',
  stock: 'Müsait Oda',
  noChange: 'Değişiklik Yok',
  closed: 'Kapalı',
  open: 'Açık',
  restrictions: 'Kısıtlamalar',
  minStay: 'Min. Konaklama',
  closedArrival: 'Girişe Kapalı',
  closedDepart: 'Çıkışa Kapalı',
  cancel: 'İptal',
  apply: 'Uygula',
  analyzingMarket: 'Pazar Analiz Ediliyor...',
  generateStrategy: 'Strateji Oluştur',
  applyAdjustment: 'Ayarlamayı Uygula',

  // Website Builder
  builderTitle: 'Web Sitesi Düzenleyici',
  builderDesc: 'Sürükle bırak yapısıyla otelinizin web sitesini tasarlayın.',
  heroSection: 'Karşılama Alanı',
  heroTitle: 'Ana Başlık',
  heroSubtitle: 'Alt Başlık',
  heroImage: 'Arkaplan Görseli',
  contentSections: 'İçerik Bölümleri',
  showAbout: 'Hakkımızda Göster',
  showRooms: 'Odaları Göster',
  showContact: 'İletişim Göster',
  showGallery: 'Galeri Göster',
  primaryColor: 'Ana Renk Teması',
  sitePublished: 'Siteniz Yayında!',
  publishing: 'Yayınlanıyor...',
  publishSite: 'Siteyi Yayınla',
  visitSite: 'Siteye Git',
  socialMedia: 'Sosyal Medya Hesapları',
  preview: 'Canlı Önizleme',
  chatWithUs: 'Bizimle Sohbet Edin',
  exportSite: 'Kendi Sunucuna Yükle',
  exportDesc: 'Kaynak kodlarını indirip kendi hostinginize yükleyebilirsiniz.',
  downloadCode: 'Kodları İndir',
  customHtml: 'Özel HTML Alanı',
  customHtmlDesc: 'Etkinlikler veya duyurular için özel içerik ekleyin.',
  analyticsSeo: 'SEO & Analytics',
  googleAnalyticsId: 'Google Analytics ID (G-XXXX)',
  pixelId: 'Facebook Pixel ID',
  contactSettings: 'İletişim Ayarları',
  whatsappNumber: 'WhatsApp Numarası',
  phoneNumber: 'Telefon Numarası',
  exportSuccess: 'Site başarıyla dışa aktarıldı.',
  selectImage: 'Görsel Seç',
  searchImage: 'Görsel Ara (Unsplash)',
  searchPlaceholder: 'Örn: Otel, Havuz, Deniz...',

  // Calendar & Badges
  vip: 'VIP',
  returning: 'Tekrar Gelen',
  newGuest: 'Yeni',

  // Common
  saveChanges: 'Değişiklikleri Kaydet',
  saved: 'Kaydedildi!',

  // Housekeeping
  housekeepingStatus: 'Oda Durumları',
  clean: 'Temiz',
  dirty: 'Kirli',
  inspect: 'Kontrol',
  markClean: 'Temiz',
  markDirty: 'Kirli',
  markInspect: 'Kontrole Gönder',

  // Booking Engine
  bookingPreview: 'Rezervasyon Motoru Önizleme',
  bookingPreviewSub: 'Misafirlerinizin web sitenizde göreceği ekran.',
  checkInDate: 'Giriş Tarihi',
  checkOutDate: 'Çıkış Tarihi',
  total: 'Toplam',
  roomSelection: 'Oda Seçimi',
  guestDetails: 'Misafir Bilgileri',
  securePayment: 'Güvenli Ödeme',
  completeBooking: 'Rezervasyonu Tamamla',
  night: 'Gece',
  back: 'Geri',
  continueDetails: 'Bilgileri Gir',
  continuePayment: 'Ödemeye Geç',
  firstName: 'Adınız',
  lastName: 'Soyadınız',
  bookingEmail: 'E-posta Adresi',
  bookingPhone: 'Telefon Numarası',
  sslSecure: '256-bit SSL ile güvenli ödeme',
  embedOnWebsite: 'Web Siteme Ekle',
  embedTitle: 'Rezervasyon Motorunu Entegre Et',
  embedDesc: 'Aşağıdaki kodu web sitenizin <body> etiketleri arasına yapıştırın.',

  // Channel Manager
  channelManager: 'Kanal Yöneticisi',
  channelDesc: 'Tüm satış kanallarını tek ekrandan yönetin.',
  simulateBooking: 'Satış Simüle Et',
  forceSync: 'Tümünü Eşitle',
  syncingChannels: 'Kanallar Eşitleniyor...',
  incomingBooking: 'Yeni Rezervasyon Geldi!',
  incomingBookingDesc: 'Booking.com üzerinden yeni bir satış sisteme düştü.',
  liveConnection: 'Bağlı',
  notConnected: 'Bağlı Değil',
  commission: 'Komisyon',
  lastSync: 'Son Eşitleme',
  configure: 'Ayarlar',
  connectChannel: 'Bağla',
  disconnectChannel: 'Bağlantıyı Kes',
  channelSettings: 'Kanal Ayarları',
  hotelId: 'Otel ID',
  apiKey: 'API Anahtarı',
  roomMapping: 'Oda Eşleştirme',
  mapRoomsDesc: 'PMS oda tiplerini kanaldaki karşılıklarıyla eşleştirin.',
  autoSync: 'Otomatik Senkronizasyon',
  autoSyncDesc: 'Değişiklikleri anında kanallara gönder.',

  // Reviews
  guestReputation: 'Misafir İtibarı',
  aiInsight: 'Yapay Zeka Analizi',
  aiAnalyzing: 'Analiz Ediliyor...',
  executiveSummary: 'Yönetici Özeti',
  sentiment: 'Duygu Durumu',
  suggestedAction: 'Önerilen Aksiyon',
  draftReply: 'Taslak Yanıt',
  draftResponse: 'Yapay Zeka Yanıt Taslağı',
  writing: 'Yazılıyor...',
  edit: 'Düzenle',
  publish: 'Yayınla',

  // Dashboard
  welcome: 'Hoşgeldiniz',
  welcomeSub: 'İşte otelinizin bugünkü durumu.',
  systemOperational: 'Sistem Aktif',
  todayArrivals: 'Bugün Gelen',
  vipGuests: 'VIP Misafir',
  activeReservations: 'Aktif Rezervasyon',
  vsLastWeek: 'geçen haftaya göre',
  totalRevenue: 'Toplam Gelir',
  avgPerRoom: 'oda başına ort.',
  adr: 'Ort. Günlük Fiyat (ADR)',
  revpar: 'RevPAR',
  occupancyForecast: 'Doluluk Tahmini',
  revenueTrends: 'Gelir Trendleri',

  // Calendar
  newReservation: 'Yeni Rezervasyon',
  threeDays: '3 Gün',
  week: 'Hafta',
  twoWeeks: '2 Hafta',
  confirmed: 'Onaylı',
  checkedIn: 'Giriş Yaptı',
  checkedOut: 'Çıkış Yaptı',
  room: 'Oda',
  createReservation: 'Rezervasyon Oluştur',
  editReservation: 'Rezervasyonu Düzenle',
  guestName: 'Misafir Adı',
  totalAmount: 'Toplam Tutar',
  paymentStatus: 'Ödeme Durumu',
  paid: 'Ödendi',
  unpaid: 'Ödenmedi',
  source: 'Kaynak',
  roomOccupied: 'Seçilen tarihlerde oda dolu!',
  invalidDates: 'Geçersiz tarih aralığı.',
  selectedDate: 'Seçilen Tarih',
  availableRooms: 'Müsait Odalar',
  bookThisRoom: 'Bu Odayı Seç',
  actions: 'İşlemler',
  checkInAction: 'Check-in Yap',
  checkOutAction: 'Check-out Yap',
  refundAction: 'İade Et',
  cancelAction: 'İptal Et',
  syncedSuccessfully: 'Eşitleme Başarılı',
  incomingBookingCalendarTitle: 'Yeni Rezervasyon',
  incomingBookingCalendarDesc: 'Kanal üzerinden satış geldi:',
  selectBoardType: 'Pansiyon Tipi',

  // Reporting
  smartReporting: 'Akıllı Raporlama',
  reportingDesc: 'Gerçek zamanlı performans metrikleri ve yapay zeka pazar analizi.',
  generateAiReport: 'Yapay Zeka Raporu Oluştur',
  analyzing: 'Analiz Ediliyor...',
  last7Days: 'Son 7 Gün',
  last30Days: 'Son 30 Gün',
  thisYear: 'Bu Yıl',
  revenueTrendAnalysis: 'Gelir Trend Analizi',
  strategicAdvice: 'Stratejik Tavsiye',
  marketAnalysis: 'Pazar Analizi',
  aiExecutiveSummary: 'Yapay Zeka Yönetici Özeti',
  revenueOccupancyTrend: 'Gelir & Doluluk Trendi',
  adrTrend: 'Ort. Günlük Fiyat (ADR) Trendi',
  bookingsBySource: 'Kaynağa Göre Rezervasyonlar',
  bookings: 'Rezervasyon',
  cancellationRate: 'İptal Oranı',
  confirmedBookings: 'Onaylı Rezervasyonlar',
  other: 'Diğer',

  // Register & Login
  registerTitle: 'Otelini Kaydet',
  registerSub: 'Butik otelinizi dakikalar içinde yönetmeye başlayın.',
  billingInfo: 'Fatura Bilgileri',
  companyName: 'Şirket Ünvanı',
  taxId: 'Vergi No (VKN/TCKN)',
  taxOffice: 'Vergi Dairesi',
  contactInfo: 'İletişim Bilgileri',
  websiteUrl: 'Web Sitesi Adresi',
  websitePlaceholder: 'https://...',
  phone: 'Telefon',
  email: 'E-posta',
  password: 'Şifre',
  continueToSetup: 'Kuruluma Devam Et',
  loginTitle: 'Yönetici Girişi',
  loginSub: 'Otel yönetim paneline erişmek için giriş yapın.',
  loginButton: 'Giriş Yap',
  orContinue: 'veya şununla devam et',
  demoButton: 'Demo Hesabı İncele',
  noAccount: 'Hesabınız yok mu?',
  registerLink: 'Hemen Kayıt Ol',
  invalidCredentials: 'Hatalı e-posta veya şifre.',

  // Login Features
  loginHeadline: 'Butik Otelciliğin Geleceği',
  loginSubHeadline: 'Yapay zeka destekli yönetim, kanal senkronizasyonu ve kusursuz misafir deneyimi tek platformda.',
  loginFeature1Title: 'Yapay Zeka Asistanı',
  loginFeature1Desc: 'Yorumları analiz eder, fiyat önerir ve misafir mesajlarını yanıtlar.',
  loginFeature2Title: 'Kanal Yöneticisi',
  loginFeature2Desc: 'Booking.com, Expedia ve diğerleri ile çift yönlü tam entegrasyon.',
  loginFeature3Title: 'Güvenli Altyapı',
  loginFeature3Desc: 'Bulut tabanlı, KVKK uyumlu ve her yerden erişilebilir sistem.',
  testimonialQuote: "Aura PMS sayesinde doluluk oranımızı %40 artırdık. Kullanımı inanılmaz kolay!",
  testimonialAuthor: "Zeynep K.",
  testimonialRole: "Otel Müdürü, Alaçatı",
  trustedBy: "2000+ BUTİK OTEL TARAFINDAN GÜVENİLİYOR",

  // Onboarding
  setupWizard: 'Otel Kurulum Sihirbazı',
  analyzingSite: 'Web Siteniz Analiz Ediliyor...',
  extractingData: 'Otel Bilgileri Çekiliyor...',
  detectingRooms: 'Oda Tipleri Algılanıyor...',
  foundInfo: 'Bilgilerinizi Bulduk',
  scannedSocials: 'Algılanan Sosyal Medya',
  roomSetup: 'Oda Kurulumu',
  roomSetupDesc: 'Web sitenizden algılanan oda tiplerini doğrulayın.',
  quantity: 'Adet',
  price: 'Fiyat',
  finishSetup: 'Kurulumu Tamamla',

  // Settings
  generalInfo: 'Genel Bilgiler',
  locationMap: 'Konum & Harita',
  roomDefinitions: 'Oda Tanımları',
  amenitiesPhotos: 'Özellikler & Fotoğraflar',
  legalKbs: 'Yasal & KBS',
  starRating: 'Yıldız Sayısı',
  description: 'Açıklama',
  baseCurrency: 'Para Birimi',
  appLanguage: 'Uygulama Dili',
  policies: 'Politikalar',
  checkIn: 'Giriş Saati',
  checkOut: 'Çıkış Saati',
  cancellationPolicy: 'İptal Politikası',
  pricingInventory: 'Fiyatlandırma & Envanter',
  totalRooms: 'Toplam Oda Sayısı',
  roomSize: 'Oda Büyüklüğü (m²)',
  capacityBoard: 'Kapasite & Pansiyon',
  maxAdults: 'Maks. Yetişkin',
  maxChildren: 'Maks. Çocuk',
  allowedBoardTypes: 'Geçerli Pansiyon Tipleri',
  roomImages: 'Oda Görselleri',
  createRoomCategory: 'Yeni Oda Kategorisi Ekle',
  kbsSettings: 'KBS (Kimlik Bildirim) Ayarları',
  kbsDesc: 'Emniyet Genel Müdürlüğü / Jandarma sistemine otomatik gönderim.',
  facilityCode: 'Tesis Kodu',
  kbsPassword: 'KBS Şifresi',
  lawEnforcementType: 'Kolluk Kuvveti',
  police: 'Polis Bölgesi',
  gendarmerie: 'Jandarma Bölgesi',
  autoSend: 'Otomatik Gönderim (Her Gece 00:00)',
  lastKbsReport: 'Son Raporlama',
  manualSend: 'Şimdi Gönder',
  sendingKbs: 'Gönderiliyor...',
  kbsSuccess: 'Başarılı!',
  paymentSettings: 'Sanal POS Ayarları',
  enableProvider: 'Aktif Et',
  secretKey: 'Gizli Anahtar (Secret Key)',
  merchantId: 'Mağaza No (Merchant ID)',
  eInvoiceSettings: 'E-Fatura Entegrasyonu',
  username: 'Kullanıcı Adı',

  // Invoices
  invoicesTitle: 'Fatura Yönetimi',
  invoicesDesc: 'E-Fatura ve E-Arşiv faturalarınızı oluşturun ve takip edin.',
  allInvoices: 'Tüm Faturalar',
  createInvoice: 'Fatura Oluştur',
  integrations: 'Entegrasyonlar',
  invoiceNumber: 'Fatura No',
  date: 'Tarih',
  customer: 'Müşteri',
  type: 'Tip',
  amount: 'Tutar',
  status: 'Durum',
  draft: 'Taslak',
  sent: 'Gönderildi',
  cancelled: 'İptal',
  selectReservation: 'Rezervasyon Seçin',
  selectGuest: 'Misafir Seçiniz...',
  invoiceType: 'Fatura Tipi',
  issuerInfoReady: 'Gönderici Bilgileri Hazır',
  missingBillingInfo: 'Eksik Fatura Bilgileri',
  missingBillingDesc: 'Lütfen Ayarlar > Genel kısmından şirket bilgilerinizi tamamlayın.',
  generatingInvoice: 'Oluşturuluyor...',
  issueInvoice: 'Faturayı Kes',
  invoicePreview: 'Fatura Önizleme',
  previewDesc: 'Oluşturulan fatura burada görüntülenecektir.',
  connect: 'Bağla',
  connected: 'Bağlandı',

  // Footer
  whatsappSupport: 'WhatsApp Destek Hattı',
  copyright: '© 2025 Aura PMS. Tüm hakları saklıdır.',

  // Live Chat
  typeMessage: 'Mesaj yazın...',
  noActiveChats: 'Aktif sohbet seçilmedi',

  // Nested Types
  roomTypes: {
    'Standard': 'Standart Oda',
    'Deluxe': 'Deluxe Oda',
    'Suite': 'Suit Oda',
    'Garden Villa': 'Bahçe Villa',
  },
  boardTypes: {
    'Room Only': 'Sadece Oda',
    'Bed & Breakfast': 'Oda Kahvaltı',
    'Half Board': 'Yarım Pansiyon',
    'Full Board': 'Tam Pansiyon',
    'All Inclusive': 'Her Şey Dahil',
  },
  roomDescriptions: {
    'Standard': 'Konforlu ve ekonomik.',
    'Deluxe': 'Geniş ve ferah.',
    'Suite': 'Lüks ve özel.',
    'Garden Villa': 'Doğa ile iç içe.'
  },
  // Guide Steps
  step1Title: 'Adım 1',
  step1Desc: 'Panel üzerinden otel durumunuzu kontrol edin.',
  step2Title: 'Adım 2',
  step2Desc: 'Takvimden rezervasyonlarınızı yönetin.',
  step3Title: 'Adım 3',
  step3Desc: 'Oda temizlik durumlarını güncelleyin.',
  step4Title: 'Adım 4',
  step4Desc: 'Otel ayarlarınızı ve politikalarınızı yapılandırın.',
  step5Title: 'Adım 5',
  step5Desc: 'Kanal yöneticisi ile satışları artırın.',
  guideTitle: 'Kullanım Kılavuzu',
  guideDesc: 'Aura PMS sistemini verimli kullanmak için adımları takip edin.',
  newBookingTitle: 'Yeni Rezervasyon',
  newBookingBody: 'Sisteme yeni bir rezervasyon eklendi.',
  cancellationTitle: 'İptal İşlemi',
  cancellationBody: 'Bir rezervasyon iptal edildi.',
};

const en = {
  // Landing Page
  lpHeroTitle: "The Future of",
  lpHeroTitleHighlight: "Boutique Hospitality",
  lpHeroSub: "Automate operations, maximize occupancy, and deliver a seamless guest experience with Aura PMS.",
  lpCtaStart: "Start Free",
  lpCtaLogin: "Manager Login",
  lpFeatAI: "AI Assistant",
  lpFeatAIDesc: "Smart suggestions for pricing strategies and guest responses.",
  lpFeatSync: "Channel Sync",
  lpFeatSyncDesc: "2-way instant connection with Booking, Expedia, and Airbnb.",
  lpFeatRes: "Smart Booking",
  lpFeatResDesc: "Get commission-free direct bookings from your website.",
  lpStat1: "40% Revenue Growth",
  lpStat2: "2000+ Happy Hotels",
  lpStat3: "24/7 Support",
  lpTestimonial1: "Since switching to Aura, our operational load has been cut in half. The pricing suggestions are incredible!",
  lpTestimonial1Auth: "Jane D. - Santorini",
  lpTestimonial2: "The interface is so modern and fast that our reception staff started using it without training.",
  lpTestimonial2Auth: "Mark S. - London",
  lpBenefitTitle: "Why Aura?",
  lpBenefit1: "Cloud-Based & Secure",
  lpBenefit2: "Mobile-First Management",
  lpBenefit3: "Advanced Reporting",
  lpFooterText: "Next-gen technology for boutique hotels.",

  // Sidebar
  dashboard: 'Dashboard',
  calendar: 'Calendar',
  housekeeping: 'Housekeeping',
  channels: 'Channel Manager',
  reviews: 'Guest Reviews',
  bookingEngine: 'Booking Engine',
  settings: 'Property Settings',
  guide: 'Setup & Guide',
  logout: 'Logout',
  role: 'Manager',
  websiteBuilder: 'Website Management',
  messages: 'Messages',
  reporting: 'Reporting',
  invoices: 'Invoices',
  pricing: 'Pricing & Revenue',
  theme: 'Theme',
  lightMode: 'Light Mode',
  darkMode: 'Dark Mode',

  // Operations & Maintenance
  operationsCenter: 'Operations Center',
  operationsDesc: 'Manage housekeeping and facility maintenance.',
  maintenance: 'Maintenance',
  createTicket: 'Create Ticket',
  issue: 'Issue',
  priority: 'Priority',
  reported: 'Reported',
  markResolved: 'Mark Resolved',
  noTickets: 'No maintenance tickets found.',
  reportIssue: 'Report Issue',
  issueDesc: 'Issue Description',
  submitTicket: 'Submit Ticket',
  selectRoom: 'Select Room...',
  priorityLow: 'Low',
  priorityMedium: 'Medium',
  priorityHigh: 'High',
  priorityCritical: 'Critical',
  statusOpen: 'Open',
  statusInProgress: 'In Progress',
  statusResolved: 'Resolved',
  reporter: 'Reporter',

  // Public Website
  navAbout: 'About',
  navRooms: 'Rooms',
  navContact: 'Contact',
  bookNow: 'Book Now',
  checkAvailability: 'Check Availability',
  startFrom: 'Starting from',
  viewAll: 'View All',
  ourRooms: 'Our Rooms',
  gallery: 'Gallery',
  welcomePublic: 'Welcome',
  newsletter: 'Newsletter',
  join: 'Join',
  footerDesc: 'Luxury living in the heart of the city.',
  guestExperiences: 'Guest Experiences',
  contactUs: 'Contact Us',
  search: 'Search',
  guests: 'Guests',
  adults: 'Adults',
  children: 'Children',
  bookYourStay: 'Book Your Stay',

  // Website Builder Defaults
  defaultHeroTitle: 'Welcome to Paradise',
  defaultHeroSubtitle: 'Experience luxury and comfort',
  aboutContent: 'Experience luxury in the heart of the Aegean coast. We invite you to enjoy our world-class amenities and breathtaking views.',
  aboutTitle: 'A Sanctuary for the Senses',
  mockReview1: 'Amazing stay! The views are breathtaking.',
  mockReview2: 'Staff was incredibly helpful.',

  // Dashboard Quick Actions
  quickActions: 'Quick Actions',
  quickNewRes: 'New Reservation',
  quickPricing: 'Update Prices',
  quickHousekeeping: 'Check Rooms',
  quickChannel: 'Sync Channels',

  // Pricing Module & Bulk Update
  pricingTitle: 'Pricing & Revenue Management',
  pricingDesc: 'Bulk updates, inventory management, and competitor analysis.',
  bulkUpdate: 'Bulk Update',
  competitors: 'Competitor Analysis',
  smartSuggestions: 'Smart Insights',
  dateRange: 'Date Range',
  applyTo: 'Apply to Room Types',
  priceUpdate: 'Price Update',
  inventoryUpdate: 'Inventory (Stock)',
  stopSale: 'Stop Sale',
  openSale: 'Open Sale',
  closeSale: 'Close Sale',
  currentPrice: 'Current Price',
  newPrice: 'New Price',
  applyUpdates: 'Apply Changes',
  competitorName: 'Competitor Hotel Name',
  addCompetitor: 'Add Competitor',
  myPrice: 'Your Price',
  marketAvg: 'Market Avg',
  diff: 'Diff',
  suggestionLower: 'Lower Price',
  suggestionRaise: 'Raise Price',
  suggestionHold: 'Hold Price',
  suggestionLowerDesc: 'You are 10% higher than competitors. Consider a discount to boost occupancy.',
  suggestionRaiseDesc: 'You are below market avg and demand is high. Consider raising rates.',
  autoAdjust: 'Auto Adjust',
  insightMarket: 'Market Position',
  insightDemand: 'Demand Alert',
  insightOpportunity: 'Opportunity',
  flashSale: 'Flash Sale',
  quickPriceUpdate: 'Quick Price Update',
  adjustInventory: 'Adjust Inventory',
  toggleStopSale: 'Toggle Stop Sale',
  onlinePrice: 'Online Price',
  agencyPrice: 'Agency Price',
  history: 'History',
  changeLog: 'Price Change Logs',
  oldVal: 'Old',
  newVal: 'New',
  user: 'User',
  changeDate: 'Change Date',
  targetDate: 'Target Date',

  // Bulk Update Specific
  applyChangesTo: 'Apply changes to:',
  start: 'Start',
  end: 'End',
  applyOnDays: 'Apply on Days',
  selectAll: 'Select All',
  weekdaysOnly: 'Weekdays Only',
  weekendsOnly: 'Weekends Only',
  bulkNote: 'Note: Leave fields blank if you do not want to update them. Only filled fields will be applied.',
  basePrice: 'Base Price',
  online: 'Online',
  agency: 'Agency',
  inventory: 'Inventory',
  stock: 'Stock',
  noChange: 'No Change',
  closed: 'Closed',
  open: 'Open',
  restrictions: 'Restrictions',
  minStay: 'Min Stay',
  closedArrival: 'Closed Arrival',
  closedDepart: 'Closed Depart',
  cancel: 'Cancel',
  apply: 'Apply',
  analyzingMarket: 'Analyzing Market...',
  generateStrategy: 'Generate Strategy',
  applyAdjustment: 'Apply Adjustment',

  // Website Builder
  builderTitle: 'Website Builder',
  builderDesc: 'Design your hotel website with drag and drop simplicity.',
  heroSection: 'Hero Section',
  heroTitle: 'Hero Title',
  heroSubtitle: 'Hero Subtitle',
  heroImage: 'Background Image',
  contentSections: 'Content Sections',
  showAbout: 'Show About',
  showRooms: 'Show Rooms',
  showContact: 'Show Contact',
  showGallery: 'Show Gallery',
  primaryColor: 'Primary Color',
  sitePublished: 'Site Published!',
  publishing: 'Publishing...',
  publishSite: 'Publish Site',
  visitSite: 'Visit Site',
  socialMedia: 'Social Media Accounts',
  preview: 'Live Preview',
  chatWithUs: 'Chat With Us',
  exportSite: 'Self-Host Export',
  exportDesc: 'Download source code to host on your own server.',
  downloadCode: 'Download Code',
  customHtml: 'Custom HTML Module',
  customHtmlDesc: 'Add custom content block for events or announcements.',
  analyticsSeo: 'SEO & Analytics',
  googleAnalyticsId: 'Google Analytics ID (G-XXXX)',
  pixelId: 'Facebook Pixel ID',
  contactSettings: 'Contact Settings',
  whatsappNumber: 'WhatsApp Number',
  phoneNumber: 'Phone Number',
  exportSuccess: 'Site exported successfully.',
  selectImage: 'Select Image',
  searchImage: 'Search Image (Unsplash)',
  searchPlaceholder: 'e.g., Hotel, Pool, Beach...',

  // Calendar & Badges
  vip: 'VIP',
  returning: 'Returning',
  newGuest: 'New',

  // Common
  saveChanges: 'Save Changes',
  saved: 'Saved!',

  // Housekeeping
  housekeepingStatus: 'Housekeeping Status',
  clean: 'Clean',
  dirty: 'Dirty',
  inspect: 'Inspection',
  markClean: 'Mark Clean',
  markDirty: 'Mark Dirty',
  markInspect: 'Mark Inspect',

  // Booking Engine
  bookingPreview: 'Booking Engine Preview',
  bookingPreviewSub: 'What your guests see on your website.',
  checkInDate: 'Check-in',
  checkOutDate: 'Check-out',
  total: 'Total',
  roomSelection: 'Room Selection',
  guestDetails: 'Guest Details',
  securePayment: 'Secure Payment',
  completeBooking: 'Complete Booking',
  night: 'night',
  back: 'Back',
  continueDetails: 'Continue to Details',
  continuePayment: 'Continue to Payment',
  firstName: 'First Name',
  lastName: 'Last Name',
  bookingEmail: 'Email Address',
  bookingPhone: 'Phone Number',
  sslSecure: 'Secure payment with 256-bit SSL',
  embedOnWebsite: 'Embed on Website',
  embedTitle: 'Integrate Booking Engine',
  embedDesc: 'Paste the code below into your website body tags.',

  // Channel Manager
  channelManager: 'Channel Manager',
  channelDesc: 'Manage all your sales channels from one place.',
  simulateBooking: 'Simulate Sale',
  forceSync: 'Force Sync',
  syncingChannels: 'Syncing Channels...',
  incomingBooking: 'New Booking Received!',
  incomingBookingDesc: 'A new reservation arrived from Booking.com',
  liveConnection: 'Connected',
  notConnected: 'Disconnected',
  commission: 'Commission',
  lastSync: 'Last Sync',
  configure: 'Settings',
  connectChannel: 'Connect',
  disconnectChannel: 'Disconnect',
  channelSettings: 'Channel Settings',
  hotelId: 'Hotel ID',
  apiKey: 'API Key',
  roomMapping: 'Room Mapping',
  mapRoomsDesc: 'Map your PMS room types to channel room IDs.',
  autoSync: 'Auto-Sync',
  autoSyncDesc: 'Automatically push changes to channels.',

  // Reviews
  guestReputation: 'Guest Reviews',
  aiInsight: 'AI Insight',
  aiAnalyzing: 'Analyzing...',
  executiveSummary: 'Executive Summary',
  sentiment: 'Sentiment',
  suggestedAction: 'Suggested Action',
  draftReply: 'Draft Reply',
  draftResponse: 'AI Draft Response',
  writing: 'Writing...',
  edit: 'Edit',
  publish: 'Publish',

  // Dashboard
  welcome: 'Welcome',
  welcomeSub: 'Here is your hotel status today.',
  systemOperational: 'System Active',
  todayArrivals: 'Arrivals Today',
  vipGuests: 'VIP Guests',
  activeReservations: 'Active Reservations',
  vsLastWeek: 'vs last week',
  totalRevenue: 'Total Revenue',
  avgPerRoom: 'avg per room',
  adr: 'ADR',
  revpar: 'RevPAR',
  occupancyForecast: 'Occupancy Forecast',
  revenueTrends: 'Revenue Trends',

  // Calendar
  newReservation: 'New Reservation',
  threeDays: '3 Days',
  week: 'Week',
  twoWeeks: '2 Weeks',
  confirmed: 'Confirmed',
  checkedIn: 'Checked In',
  checkedOut: 'Checked Out',
  room: 'Room',
  createReservation: 'Create Reservation',
  editReservation: 'Edit Reservation',
  guestName: 'Guest Name',
  totalAmount: 'Total Amount',
  paymentStatus: 'Payment Status',
  paid: 'Paid',
  unpaid: 'Unpaid',
  source: 'Source',
  roomOccupied: 'Room occupied on selected dates!',
  invalidDates: 'Invalid date range.',
  selectedDate: 'Selected Date',
  availableRooms: 'Available Rooms',
  bookThisRoom: 'Book This Room',
  actions: 'Actions',
  checkInAction: 'Check-in',
  checkOutAction: 'Check-out',
  refundAction: 'Refund',
  cancelAction: 'Cancel',
  syncedSuccessfully: 'Synced Successfully',
  incomingBookingCalendarTitle: 'New Booking',
  incomingBookingCalendarDesc: 'New sale via channel:',
  selectBoardType: 'Board Type',

  // Reporting
  smartReporting: 'Smart Reporting',
  reportingDesc: 'Real-time performance metrics and AI market analysis.',
  generateAiReport: 'Generate AI Report',
  analyzing: 'Analyzing...',
  last7Days: 'Last 7 Days',
  last30Days: 'Last 30 Days',
  thisYear: 'This Year',
  revenueTrendAnalysis: 'Revenue Trend Analysis',
  strategicAdvice: 'Strategic Advice',
  marketAnalysis: 'Market Analysis',
  aiExecutiveSummary: 'AI Executive Summary',
  revenueOccupancyTrend: 'Revenue & Occupancy Trend',
  adrTrend: 'ADR Trend',
  bookingsBySource: 'Bookings by Source',
  bookings: 'Bookings',
  cancellationRate: 'Cancellation Rate',
  confirmedBookings: 'Confirmed Bookings',
  other: 'Other',

  // Register & Login
  registerTitle: 'Register Hotel',
  registerSub: 'Start managing your boutique hotel in minutes.',
  billingInfo: 'Billing Info',
  companyName: 'Company Name',
  taxId: 'Tax ID',
  taxOffice: 'Tax Office',
  contactInfo: 'Contact Info',
  websiteUrl: 'Website URL',
  websitePlaceholder: 'https://...',
  phone: 'Phone',
  email: 'Email',
  password: 'Password',
  continueToSetup: 'Continue to Setup',
  loginTitle: 'Manager Login',
  loginSub: 'Login to access the hotel management panel.',
  loginButton: 'Login',
  orContinue: 'or continue with',
  demoButton: 'View Demo Account',
  noAccount: 'Don\'t have an account?',
  registerLink: 'Register Now',
  invalidCredentials: 'Invalid email or password.',

  // Login Features
  loginHeadline: 'The Future of Boutique Hospitality',
  loginSubHeadline: 'AI-powered management, channel sync, and seamless guest experience in one platform.',
  loginFeature1Title: 'AI Assistant',
  loginFeature1Desc: 'Analyzes reviews, suggests prices, and responds to guest messages.',
  loginFeature2Title: 'Channel Manager',
  loginFeature2Desc: '2-way full integration with Booking.com, Expedia, and others.',
  loginFeature3Title: 'Secure Infrastructure',
  loginFeature3Desc: 'Cloud-based, GDPR compliant, and accessible from anywhere.',
  testimonialQuote: "Thanks to Aura PMS, we increased our occupancy by 40%. It's incredibly easy to use!",
  testimonialAuthor: "Jane D.",
  testimonialRole: "Hotel Manager, Santorini",
  trustedBy: "TRUSTED BY 2000+ BOUTIQUE HOTELS",

  // Onboarding
  setupWizard: 'Hotel Setup Wizard',
  analyzingSite: 'Analyzing Website...',
  extractingData: 'Extracting Hotel Info...',
  detectingRooms: 'Detecting Room Types...',
  foundInfo: 'We Found Your Info',
  scannedSocials: 'Detected Social Media',
  roomSetup: 'Room Setup',
  roomSetupDesc: 'Verify room types detected from your website.',
  quantity: 'Qty',
  price: 'Price',
  finishSetup: 'Finish Setup',

  // Settings
  generalInfo: 'General Info',
  locationMap: 'Location & Map',
  roomDefinitions: 'Room Definitions',
  amenitiesPhotos: 'Amenities & Photos',
  legalKbs: 'Legal & KBS',
  starRating: 'Star Rating',
  description: 'Description',
  baseCurrency: 'Currency',
  appLanguage: 'App Language',
  policies: 'Policies',
  checkIn: 'Check-in Time',
  checkOut: 'Check-out Time',
  cancellationPolicy: 'Cancellation Policy',
  pricingInventory: 'Pricing & Inventory',
  totalRooms: 'Total Rooms',
  roomSize: 'Room Size (m²)',
  capacityBoard: 'Capacity & Board',
  maxAdults: 'Max Adults',
  maxChildren: 'Max Children',
  allowedBoardTypes: 'Allowed Board Types',
  roomImages: 'Room Images',
  createRoomCategory: 'Create New Room Category',
  kbsSettings: 'KBS Settings',
  kbsDesc: 'Automatic submission to law enforcement.',
  facilityCode: 'Facility Code',
  kbsPassword: 'KBS Password',
  lawEnforcementType: 'Law Enforcement Type',
  police: 'Police Zone',
  gendarmerie: 'Gendarmerie Zone',
  autoSend: 'Auto Send (Every Night 00:00)',
  lastKbsReport: 'Last Report',
  manualSend: 'Send Now',
  sendingKbs: 'Sending...',
  kbsSuccess: 'Success!',
  paymentSettings: 'POS Settings',
  enableProvider: 'Enable',
  secretKey: 'Secret Key',
  merchantId: 'Merchant ID',
  eInvoiceSettings: 'E-Invoice Integration',
  username: 'Username',

  // Invoices
  invoicesTitle: 'Invoice Management',
  invoicesDesc: 'Create and track E-Invoices and E-Archive invoices.',
  allInvoices: 'All Invoices',
  createInvoice: 'Create Invoice',
  integrations: 'Integrations',
  invoiceNumber: 'Invoice #',
  date: 'Date',
  customer: 'Customer',
  type: 'Type',
  amount: 'Amount',
  status: 'Status',
  draft: 'Draft',
  sent: 'Sent',
  cancelled: 'Cancelled',
  selectReservation: 'Select Reservation',
  selectGuest: 'Select Guest...',
  invoiceType: 'Invoice Type',
  issuerInfoReady: 'Issuer Info Ready',
  missingBillingInfo: 'Missing Billing Info',
  missingBillingDesc: 'Please complete company details in Settings > General.',
  generatingInvoice: 'Generating...',
  issueInvoice: 'Issue Invoice',
  invoicePreview: 'Invoice Preview',
  previewDesc: 'Generated invoice will appear here.',
  connect: 'Connect',
  connected: 'Connected',

  // Footer
  whatsappSupport: 'WhatsApp Support',
  copyright: '© 2025 Aura PMS. All rights reserved.',

  // Live Chat
  typeMessage: 'Type a message...',
  noActiveChats: 'No active chat selected',

  // Nested Types
  roomTypes: {
    'Standard': 'Standard Room',
    'Deluxe': 'Deluxe Room',
    'Suite': 'Suite',
    'Garden Villa': 'Garden Villa',
  },
  boardTypes: {
    'Room Only': 'Room Only',
    'Bed & Breakfast': 'Bed & Breakfast',
    'Half Board': 'Half Board',
    'Full Board': 'Full Board',
    'All Inclusive': 'All Inclusive',
  },
  roomDescriptions: {
    'Standard': 'Compact and affordable.',
    'Deluxe': 'Spacious and comfortable.',
    'Suite': 'Luxury with a view.',
    'Garden Villa': 'Private and serene.'
  },
  // Guide Steps
  step1Title: 'Step 1',
  step1Desc: 'Check your hotel status from the dashboard.',
  step2Title: 'Step 2',
  step2Desc: 'Manage your reservations from the calendar.',
  step3Title: 'Step 3',
  step3Desc: 'Update housekeeping statuses.',
  step4Title: 'Step 4',
  step4Desc: 'Configure hotel settings and policies.',
  step5Title: 'Step 5',
  step5Desc: 'Boost sales with the channel manager.',
  guideTitle: 'User Guide',
  guideDesc: 'Follow the steps to use Aura PMS efficiently.',
  newBookingTitle: 'New Booking',
  newBookingBody: 'A new reservation has been added.',
  cancellationTitle: 'Cancellation',
  cancellationBody: 'A reservation has been cancelled.',
};

export const translations: Record<Language, any> = {
  tr,
  en,
  de,
  ru,
  sv
};
